//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDG.Visuals.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int RollDirection {
            get {
                return ((int)(this["RollDirection"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>5.0</string>
  <string>4.5</string>
  <string>4.0</string>
  <string>3.5</string>
  <string>3.0</string>
  <string>2.5</string>
  <string>2.0</string>
  <string>1.5</string>
  <string>1.0</string>
  <string>.5</string>
  <string>0.0</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DeckPlateOptions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DeckPlateOptions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>10</string>
  <string>11</string>
  <string>12</string>
  <string>13</string>
  <string>14</string>
  <string>15</string>
  <string>16</string>
  <string>17</string>
  <string>18</string>
  <string>19</string>
  <string>20</string>
  <string>21</string>
  <string>22</string>
  <string>23</string>
  <string>24</string>
  <string>25</string>
  <string>26</string>
  <string>27</string>
  <string>28</string>
  <string>29</string>
  <string>30</string>
  <string>31</string>
  <string>32</string>
  <string>33</string>
  <string>34</string>
  <string>35</string>
  <string>36</string>
  <string>37</string>
  <string>38</string>
  <string>39</string>
  <string>40</string>
  <string>41</string>
  <string>42</string>
  <string>43</string>
  <string>44</string>
  <string>45</string>
  <string>46</string>
  <string>47</string>
  <string>48</string>
  <string>49</string>
  <string>50</string>
  <string>51</string>
  <string>52</string>
  <string>53</string>
  <string>54</string>
  <string>55</string>
  <string>56</string>
  <string>57</string>
  <string>58</string>
  <string>59</string>
  <string>60</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection BargeWidthOptions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["BargeWidthOptions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>0.0</string>
  <string>1.0</string>
  <string>2.0</string>
  <string>3.0</string>
  <string>4.0</string>
  <string>5.0</string>
  <string>6.0</string>
  <string>7.0</string>
  <string>8.0</string>
  <string>9.0</string>
  <string>10.0</string>
  <string>11.0</string>
  <string>12.0</string>
  <string>13.0</string>
  <string>14.0</string>
  <string>15.0</string>
  <string>16.0</string>
  <string>17.0</string>
  <string>18.0</string>
  <string>19.0</string>
  <string>20.0</string>
  <string>21.0</string>
  <string>22.0</string>
  <string>23.0</string>
  <string>24.0</string>
  <string>25.0</string>
  <string>26.0</string>
  <string>27.0</string>
  <string>28.0</string>
  <string>29.0</string>
  <string>30.0</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection BargeDepthOptions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["BargeDepthOptions"]));
            }
        }
    }
}
