//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.296.
// 
#pragma warning disable 1591

namespace MDG.BargeService.SVC {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BargeDataServiceSoap", Namespace="http://tempuri.org/")]
    public partial class BargeDataService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback DraftLevelOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBargeDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecordReadingOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BargeDataService() {
            this.Url = global::MDG.BargeService.Properties.Settings.Default.MDG_BargeService_SVC_BargeDataService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DraftLevelCompletedEventHandler DraftLevelCompleted;
        
        /// <remarks/>
        public event GetBargeDataCompletedEventHandler GetBargeDataCompleted;
        
        /// <remarks/>
        public event RecordReadingCompletedEventHandler RecordReadingCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DraftLevel", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int DraftLevel(string bargeID, string reading) {
            object[] results = this.Invoke("DraftLevel", new object[] {
                        bargeID,
                        reading});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void DraftLevelAsync(string bargeID, string reading) {
            this.DraftLevelAsync(bargeID, reading, null);
        }
        
        /// <remarks/>
        public void DraftLevelAsync(string bargeID, string reading, object userState) {
            if ((this.DraftLevelOperationCompleted == null)) {
                this.DraftLevelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDraftLevelOperationCompleted);
            }
            this.InvokeAsync("DraftLevel", new object[] {
                        bargeID,
                        reading}, this.DraftLevelOperationCompleted, userState);
        }
        
        private void OnDraftLevelOperationCompleted(object arg) {
            if ((this.DraftLevelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DraftLevelCompleted(this, new DraftLevelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetBargeData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BargeStructure GetBargeData(string bargeID) {
            object[] results = this.Invoke("GetBargeData", new object[] {
                        bargeID});
            return ((BargeStructure)(results[0]));
        }
        
        /// <remarks/>
        public void GetBargeDataAsync(string bargeID) {
            this.GetBargeDataAsync(bargeID, null);
        }
        
        /// <remarks/>
        public void GetBargeDataAsync(string bargeID, object userState) {
            if ((this.GetBargeDataOperationCompleted == null)) {
                this.GetBargeDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBargeDataOperationCompleted);
            }
            this.InvokeAsync("GetBargeData", new object[] {
                        bargeID}, this.GetBargeDataOperationCompleted, userState);
        }
        
        private void OnGetBargeDataOperationCompleted(object arg) {
            if ((this.GetBargeDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBargeDataCompleted(this, new GetBargeDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RecordReading", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RecordReading(string bargeID, int scaleReading, int instrumentReading, string draftReading) {
            object[] results = this.Invoke("RecordReading", new object[] {
                        bargeID,
                        scaleReading,
                        instrumentReading,
                        draftReading});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RecordReadingAsync(string bargeID, int scaleReading, int instrumentReading, string draftReading) {
            this.RecordReadingAsync(bargeID, scaleReading, instrumentReading, draftReading, null);
        }
        
        /// <remarks/>
        public void RecordReadingAsync(string bargeID, int scaleReading, int instrumentReading, string draftReading, object userState) {
            if ((this.RecordReadingOperationCompleted == null)) {
                this.RecordReadingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecordReadingOperationCompleted);
            }
            this.InvokeAsync("RecordReading", new object[] {
                        bargeID,
                        scaleReading,
                        instrumentReading,
                        draftReading}, this.RecordReadingOperationCompleted, userState);
        }
        
        private void OnRecordReadingOperationCompleted(object arg) {
            if ((this.RecordReadingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecordReadingCompleted(this, new RecordReadingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (string.IsNullOrEmpty(url)) {
                return false;
            }
            Uri wsUri = new Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BargeStructure {
        
        private int lengthField;
        
        private int widthField;
        
        private int heightField;
        
        private string lightDraftField;
        
        /// <remarks/>
        public int Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
        
        /// <remarks/>
        public int Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        public int Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        public string LightDraft {
            get {
                return this.lightDraftField;
            }
            set {
                this.lightDraftField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DraftLevelCompletedEventHandler(object sender, DraftLevelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DraftLevelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DraftLevelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetBargeDataCompletedEventHandler(object sender, GetBargeDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBargeDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBargeDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BargeStructure Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BargeStructure)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void RecordReadingCompletedEventHandler(object sender, RecordReadingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecordReadingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecordReadingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591